"""
Constants for graph-related operations.
"""

AGENT_ORCHESTRATOR = "orchestrator"
AGENT_COMMUNICATOR = "communicator"
AGENT_ANALYZER = "analyzer"
AGENT_MODIFIER = "modifier"
AGENT_RETRIEVER = "retriever"
AGENT_VISUALIZER = "visualizer"
AGENT_FORK = "fork"  # Fork node for parallel execution
AGENT_MERGE = "merge"  # Merge node for combining parallel results

ACTION_ADD_TRIPLES = "add_triples"
ACTION_DELETE_TRIPLES = "delete_triples"
ACTION_MERGE_ENTITIES = "merge_entities"
ACTION_RENAME_ENTITY = "rename_entity"
ACTION_UPDATE_ENTITY_LABEL = "update_entity_label"
ACTION_MODIFY_TRIPLE = "modify_triple"

STATE_MESSAGES = "messages"
STATE_CURRENT_QUESTION_ID = "current_question_id"
STATE_CURRENT_QUESTION_TEXT = "current_question_text"
STATE_QUESTIONS = "questions"
STATE_GRAPH_NODES_COUNT = "graph_nodes_count"
STATE_GRAPH_EDGES_COUNT = "graph_edges_count"
STATE_TRIPLES_COUNT = "triples_count"
STATE_ENTITIES_COUNT = "entities_count"
STATE_NEXT_AGENT = "next_agent"
STATE_VALIDATION_COMPLETE = "validation_complete"
STATE_HIDDEN_ACTIONS = "hidden_actions"
STATE_DISPLAY_ACTIONS = "display_actions"
STATE_SHOW_WIDGET = "show_widget"
STATE_WIDGET_TYPE = "widget_type"
STATE_WIDGET_DATA = "widget_data"
STATE_CONVERSATION_TURN = "conversation_turn"
STATE_CHANGES_SUMMARY = "changes_summary"
STATE_STATS = "stats"
STATE_AGENT_QUEUE = "agent_queue"
STATE_MODE = "mode"
STATE_PLAN = "plan"
STATE_NEEDS_RETRIEVAL = "needs_retrieval"
STATE_WRITE = "write"
STATE_RESPONSE_STYLE = "response_style"

