"""
Shared types for graph validator - dataclasses and enums.
This module is separate to avoid circular imports.
"""
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from enum import Enum


class ActionType(Enum):
    """Types of actions that can be triggered by responses."""
    # Display actions (visible to user)
    SHOW_TRIPLES = "show_triples"
    HIDE_TRIPLES = "hide_triples"
    HIGHLIGHT_ENTITIES = "highlight_entities"
    ASK_IMPORTANCE = "ask_importance"
    ASK_RELATION_CLARITY = "ask_relation_clarity"
    OPEN_WIDGET = "open_widget"
    CLOSE_WIDGET = "close_widget"
    SHOW_ENTITY_DETAILS = "show_entity_details"
    SHOW_CONTRADICTIONS = "show_contradictions"
    
    # Graph modification actions (hidden from user)
    ADD_TRIPLES = "add_triples"
    DELETE_TRIPLES = "delete_triples"
    MODIFY_TRIPLE = "modify_triple"  # Change relation, head, or tail
    MERGE_ENTITIES = "merge_entities"
    DELETE_ENTITY = "delete_entity"  # Delete entity and all connected triples
    RENAME_ENTITY = "rename_entity"  # Change entity name/label
    CHANGE_ENTITY_LABEL = "change_entity_label"  # Change entity type/label
    UPDATE_ENTITY_PROPERTIES = "update_entity_properties"  # Update entity metadata
    ADD_RELATION = "add_relation"  # Add relation between existing entities
    REMOVE_RELATION = "remove_relation"  # Remove specific relation edge
    CHANGE_RELATION = "change_relation"  # Change relation name
    SPLIT_ENTITY = "split_entity"  # Split one entity into multiple
    CREATE_ENTITY = "create_entity"  # Create new entity
    UPDATE_TRIPLE_RELATION = "update_triple_relation"  # Change relation in triple
    UPDATE_TRIPLE_HEAD = "update_triple_head"  # Change head entity in triple
    UPDATE_TRIPLE_TAIL = "update_triple_tail"  # Change tail entity in triple


@dataclass
class Action:
    """An action to be performed based on a response."""
    type: ActionType
    parameters: Dict[str, Any] = field(default_factory=dict)
    description: Optional[str] = None


@dataclass
class Question:
    """A question generated by the validator."""
    id: str
    text: str
    category: str  # "mistake", "discrepancy", "unclear_connection", "unclear_entity", "importance"
    context: Dict[str, Any] = field(default_factory=dict)  # Hidden context (triple IDs, entity IDs, etc.)
    priority: int = 5  # 1-10, higher = more important
    suggested_actions: List[Action] = field(default_factory=list)
    show_widget: bool = False  # Whether to show a widget when asking this question
    widget_type: Optional[str] = None  # Type of widget to show (e.g., "importance_selector", "triple_editor")
    widget_parameters: Dict[str, Any] = field(default_factory=dict)  # Parameters for the widget
    answered: bool = False  # Whether this question has been fully answered
    num_responses: int = 0  # Number of times user has responded to this question


@dataclass
class ConversationTurn:
    """A single turn in a conversation (user answer + bot response)."""
    user_answer: str
    bot_response: str
    turn_number: int


@dataclass
class Response:
    """A response to a question, containing text and hidden actions."""
    question_id: str
    text: str  # The actual response text (visible to user)
    actions: List[Action] = field(default_factory=list)  # Hidden actions to perform
    hidden_actions: List[Action] = field(default_factory=list)  # Actions that modify graph (hidden from user)
    metadata: Dict[str, Any] = field(default_factory=dict)  # Additional hidden data (triples, entities, etc.)
    show_widget: bool = False  # Whether to show a widget
    widget_type: Optional[str] = None  # Type of widget to show
    question_completed: bool = False  # Whether the LLM considers this question fully answered

